- name: Evaluate openshift-serverless Namespace
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: 'openshift-serverless'

- name: Evaluate Operator Group
  k8s:
    state: present
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    definition:
      metadata:
        name: 'openshift-serverless-operatorgroup'
        namespace: 'openshift-serverless'

- name: Evaluate Serverless Subscription
  k8s:
    state: present
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    definition:
      metadata:
        name: serverless-operator
        namespace: openshift-serverless
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: serverless-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait for Serverless subscription to complete
  shell: set -o pipefail && oc get csv -n openshift-serverless | grep serverless-operator
  register: install_status
  until: "'Succeeded' in install_status.stdout"
  retries: 20
  delay: 15
  args:
    executable: /bin/bash

- name: Evaluate KnativeEventing
  k8s:
    state: present
    api_version: operator.knative.dev/v1alpha1
    kind: KnativeEventing
    definition:
      metadata:
        name: knative-eventing
        namespace: knative-eventing
      spec: {}

- name: Evaluate KnativeServing
  k8s:
    state: present
    api_version: operator.knative.dev/v1alpha1
    kind: KnativeServing
    definition:
      metadata:
        name: knative-serving
        namespace: knative-serving
      spec: {}
