- name: Evaluate openshift-serverless Namespace
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: 'openshift-serverless'

- name: Evaluate Operator Group
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    definition:
      metadata:
        name: 'openshift-serverless-operatorgroup'
        namespace: 'openshift-serverless'

- name: Evaluate Serverless Subscription
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    definition:
      metadata:
        name: serverless-operator
        namespace: openshift-serverless
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: serverless-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait Serverless Operator To Be Running
  k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: v1
    kind: Pod
    namespace: openshift-serverless
    label_selectors:
      - name = knative-operator
    field_selectors:
      - status.phase=Running
  register: r_serverless_pod
  retries: 120
  delay: 10
  until: r_serverless_pod.resources | list | length == 1

- name: Evaluate KnativeEventing
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    api_version: operator.knative.dev/v1alpha1
    kind: KnativeEventing
    definition:
      metadata:
        name: knative-eventing
        namespace: knative-eventing
      spec: {}

- name: Evaluate KnativeServing
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    api_version: operator.knative.dev/v1alpha1
    kind: KnativeServing
    definition:
      metadata:
        name: knative-serving
        namespace: knative-serving
      spec: {}
