- hosts: localhost
  name: Install Camel K Demo
  vars:
    demo_project: camel-k-serverless
    demo_project_description: Namespace used for Camel K Serverless Demo
    demo_project_display_name: Camel K - Serverless
    verify_tls: false
  tasks:

    - name: Check Required Parameters
      fail: msg="This play requires 'server','token' and 'participants' to be defined"
      when:
        - server is not defined
        - token is not defined

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443')   }}"

    - name: Evaluate {{ demo_project }} Namespace
      k8s:
        api_key: '{{ token }}'
        host: '{{ server }}'
        validate_certs: '{{ verify_tls }}'
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ demo_project }}"
            annotations:
              openshift.io/description: "{{ demo_project_description }}"
              openshift.io/display-name: "{{ demo_project_display_name }}"

    - name: Include Minio Role
      include_role:
        name: minio

    - name: Include Serverless Role
      include_role:
        name: serverless

    - name: Include Camel K Role
      include_role:
        name: camel-k

    - name: Include Karavan Role
      include_role:
        name: karavan
